"""Build-only generation of optional break-blow signatures from inspected LR code."""
from pathlib import Path
import sys,re,json
sys.path.insert(0,str(Path(__file__).parent/'python_deps'))
import capstone
root=Path(__file__).resolve().parents[1];b=(root/'analysis/lr_updated.bin').read_bytes();old=(root/'analysis/lr_baseline.bin').read_bytes()
md=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_64);md.detail=True
rows=[]
for name,a,z in [('branch',0x3aeacf0,0x3aead8b),('property',0x3a6dee0,0x3a6dffb)]:
 data=b[a:z];mask=bytearray([255]*len(data))
 for i in md.disasm(data,a):
  if (i.group(capstone.CS_GRP_JUMP) or i.group(capstone.CS_GRP_CALL)) and i.imm_size and not a<=i.operands[0].imm<z:
   off=i.address-a+i.imm_offset;mask[off:off+i.imm_size]=bytes(i.imm_size)
  if any(op.type==capstone.x86.X86_OP_MEM and op.mem.base==capstone.x86.X86_REG_RIP for op in i.operands):
   off=i.address-a+i.disp_offset;mask[off:off+4]=bytes(4)
 pattern=b''.join(re.escape(bytes([v])) if m else b'.' for v,m in zip(data,mask))
 hits={key:[m.start() for m in re.finditer(pattern,blob,re.S)] for key,blob in [('old',old),('new',b)]}
 assert all(len(v)==1 for v in hits.values()),hits
 rows.append(dict(name=name,data=data.hex(),mask=mask.hex(),hits=hits))
 print(name,{k:[hex(x) for x in v] for k,v in hits.items()})
(root/'evidence/break_blow_patterns.json').write_text(json.dumps(rows,indent=2))
def literal(h):return '"'+''.join('\\x'+h[i:i+2] for i in range(0,len(h),2))+'"'
lines=['#pragma once','// Generated by tools/generate_break_blow.py; optional, independently validated.', 'struct BreakBlowPattern {const char* name; const char* data; const char* mask; size_t size;};','static const BreakBlowPattern breakBlowPatterns[]={']
for r in rows:lines.append('{"'+r['name']+'",'+literal(r['data'])+','+literal(r['mask'])+','+str(len(r['data'])//2)+'},')
lines.append('};');(root/'prototype/break_blow_patterns.h').write_text('\n'.join(lines)+'\n')
