"""Build-only optional stage texture setter signature, validated in both LR images."""
from pathlib import Path
import sys, re, json
sys.path.insert(0, str(Path(__file__).parent/'python_deps'))
import capstone
root=Path(__file__).resolve().parents[1]
b=(root/'analysis/lr_updated.bin').read_bytes()
a,z=0x21c1330,0x21c162f
data=b[a:z]; mask=bytearray([255]*len(data))
md=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_64); md.detail=True
for i in md.disasm(data,a):
    if (i.group(capstone.CS_GRP_JUMP) or i.group(capstone.CS_GRP_CALL)) and i.imm_size and not a<=i.operands[0].imm<z:
        off=i.address-a+i.imm_offset; mask[off:off+i.imm_size]=bytes(i.imm_size)
    if any(op.type==capstone.x86.X86_OP_MEM and op.mem.base==capstone.x86.X86_REG_RIP for op in i.operands):
        off=i.address-a+i.disp_offset; mask[off:off+4]=bytes(4)
pattern=b''.join(re.escape(bytes([v])) if m else b'.' for v,m in zip(data,mask))
hits={key:[m.start() for m in re.finditer(pattern,(root/('analysis/'+key+'.bin')).read_bytes(),re.S)] for key in ['lr_baseline','lr_updated']}
assert all(len(v)==1 for v in hits.values()),hits
def lit(value): return '"'+''.join('\\x%02x'%x for x in value)+'"'
(root/'prototype/stage_pattern.h').write_text('#pragma once\n// Generated by tools/generate_stage_pattern.py\nstatic const GamePattern stageTexturePattern={"stageTexture",'+lit(data)+','+lit(mask)+','+str(len(data))+',0};\n')
(root/'evidence/stage_texture_pattern.json').write_text(json.dumps(hits,indent=2))
print({k:[hex(x) for x in v] for k,v in hits.items()})
