from pathlib import Path
p=Path('prototype/layer2_state.h');s=p.read_text().replace('#include <map>','#include <map>\n#include <tuple>');s=s.replace('std::map<uint64_t, size_t> choices;','std::map<std::tuple<unsigned,uint32_t,uint32_t>, size_t> choices;').replace('uint32_t slot) const','uint32_t slot,uint32_t context=0) const').replace('int direction) {','int direction,uint32_t context=0) {').replace('uint64_t sample) {','uint64_t sample,uint32_t context=0) {').replace('(uint64_t(player)<<32)|slot','std::make_tuple(player,slot,context)');p.write_text(s)
p=Path('prototype/layer2_runtime.h');s=p.read_text();s=s.replace('static Layer2Selection selections;','static Layer2Selection selections, hairSelections;\nstatic std::atomic<int> hairPlayer{-1};\nstatic uint32_t activeHairs[2]{},activeFaces[2]{};\nstatic std::vector<size_t> hairChoices(uint32_t hair,uint32_t face) {\n    std::vector<size_t> result;\n    for(auto slot:{hair,face}){auto it=slots.find(slot);if(it!=slots.end())result.insert(result.end(),it->second.begin(),it->second.end());}\n    return result;\n}');s=s.replace('int player=selectedPlayer.load();if(player<0||player>1)return;','bool hairMode=hairPlayer.load()>=0;\n        int player=hairMode?hairPlayer.load():selectedPlayer.load();if(player<0||player>1)return;');s=s.replace('std::string slot="0x"+hex(req.costume);','uint32_t shownSlot=hairMode?req.hair:req.costume;\n        std::string slot="0x"+hex(shownSlot);').replace('entry.hash==req.costume','entry.hash==shownSlot').replace('currentSlotNames.find(req.costume)','currentSlotNames.find(shownSlot)');s=s.replace('text="Slot: "+slot+" Mod: "+name;','if(hairMode){auto choices=hairChoices(req.hair,req.face);size_t h=hairSelections.current(player,req.hair,req.face);name=h&&h<=choices.size()?mods[choices[h-1]].name:"Vanilla";}\n        text=(hairMode?"Hair: ":"Slot: ")+slot+" Mod: "+name;');s=s.replace('name.find("_COS_")==std::string::npos','(name.find("_COS_")==std::string::npos&&name.find("_HAIR_")==std::string::npos&&name.find("_FACE_")==std::string::npos)');s=s.replace('for(int p:{player,1-player}) {\n        auto found=', '''for(int p:{player,1-player}) {
        // Explicit hair/head selections take precedence over a costume bundle.
        auto choices=hairChoices(activeHairs[p],activeFaces[p]);
        size_t h=hairSelections.current(p,activeHairs[p],activeFaces[p]);
        if(h&&h<=choices.size()) {
            auto& mod=mods[choices[h-1]];auto file=mod.files.find(path);
            if(file!=mod.files.end()){log("LAYER2 HAIR OPEN P"+std::to_string(p+1)+" "+mod.name+" "+utf8(path.substr(gameRoot.size())));return file->second;}
        }
        auto found=''',1);s=s.replace('activeCostumes[player]=costume;','activeCostumes[player]=costume;activeHairs[player]=hair;activeFaces[player]=face;');s=s.replace('if(player<2&&selectedPlayer==static_cast<int>(player))','if(player<2&&(selectedPlayer==static_cast<int>(player)||hairPlayer==static_cast<int>(player)))');s=s.replace('activeCostumes[player]=pending.costume;routePlayer=', 'activeCostumes[player]=pending.costume;activeHairs[player]=pending.hair;activeFaces[player]=pending.face;routePlayer=');s=s.replace('if(layoutLogs++<400)','if(layoutLogs++<400||!strncmp(animation,"detail_",7)||!strncmp(animation,"cos_",4))');s=s.replace('    auto result=layoutOriginal(object,hash,animation,extra);','    if(animation&&!strcmp(animation,"detail_out")&&hairPlayer>=0)finishPreviewReload(static_cast<unsigned>(hairPlayer.load()),true);\n    auto result=layoutOriginal(object,hash,animation,extra);');s=s.replace('    // These names belong', '''    if(hash==0xdd6728d2) {
        if(!strcmp(animation,"detail_pos_1p")){hairPlayer=0;showSlotInfo();}
        else if(!strcmp(animation,"detail_pos_2p")){hairPlayer=1;showSlotInfo();}
        else if(!strcmp(animation,"detail_out")){hairPlayer=-1;showSlotInfo();}
    }
    // These names belong''');s=s.replace('int p=selectedPlayer.load();if(p<0||p>1)', 'bool hairMode=hairPlayer.load()>=0;\n        int p=hairMode?hairPlayer.load():selectedPlayer.load();if(p<0||p>1)');s=s.replace('req=requests[p];auto found=slots.find(req.costume);\n        if(!req.object||found==slots.end())return;', 'req=requests[p];auto found=slots.find(req.costume);\n        auto choices=hairMode?hairChoices(req.hair,req.face):(found!=slots.end()?found->second:std::vector<size_t>{});\n        if(!req.object||choices.empty())return;');s=s.replace('total=found->second.size();value=selections.cycle(p,req.costume,total,direction);\n        name=value?mods[found->second[value-1]].name:"Default";', 'total=choices.size();value=hairMode?hairSelections.cycle(p,req.hair,total,direction,req.face):selections.cycle(p,req.costume,total,direction);\n        name=value?mods[choices[value-1]].name:"Default";');s=s.replace('    releaseBody(req.object,handle);','    releaseBody(req.object,handle);\n    if(hairPlayer>=0){releaseBody(req.object,handle+0x38);releaseBody(req.object,handle+0x70);}');p.write_text(s)
p=Path('tools/kashira_bridge.py');s=p.read_text().replace('BRIDGE_VERSION=4','BRIDGE_VERSION=5').replace("r'[A-Z0-9]+_COS_[0-9]+'","r'[A-Z0-9]+_(?:COS|HAIR|FACE)_[0-9]+[a-z]?'").replace('Invalid costume slot','Invalid costume/hair/face slot');p.write_text(s)
p=Path('tools/KashiraPrepare/Program.cs');s=p.read_text().replace('^[A-Z0-9]+_COS_[0-9]+$','^[A-Z0-9]+_(COS|HAIR|FACE)_[0-9]+$').replace('"adapter-v2"','"adapter-v3-hair"');s=s.replace('if(slots.Length!=1)', '''// A costume bundle may also contain its face/hair mesh; its costume is primary.
   var costumes=slots.Where(s=>s.Contains("_COS_")).ToArray();
   var hairs=slots.Where(s=>s.Contains("_HAIR_")).ToArray();
   if(costumes.Length>0)slots=costumes;else if(hairs.Length>0)slots=hairs;
   if(slots.Length!=1)''');s=s.replace('Costume slot is ambiguous','Costume/hair/face slot is ambiguous');p.write_text(s)
