<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><AllowUnsafeBlocks>true</AllowUnsafeBlocks><DefineConstants>CORE</DefineConstants><GenerateAssemblyInfo>false</GenerateAssemblyInfo><NoWarn>SYSLIB0021;SYSLIB0041;SYSLIB0051</NoWarn></PropertyGroup>
<ItemGroup><Compile Include="../../external/LibOrbisPkg/LibOrbisPkg/**/*.cs" /></ItemGroup>
</Project>
