; This file is to be used with REDELBE.ini Random:enable_random_music = true AND RandomMusic:mode = fullmix.
; Here you can define a list of bgm for each character and stage (unlike in the game ui where you can only choose one)
; The setting RandomMusic:stage_probability in REDELBE.ini will control the probability that a stage theme is chosen over the character one.
;
; The name of the tracks is the one of the file extracted by SRSXtool from SE1_BGM.srst, without extension.
; If multiple tracks, separate each track with a "," 
[ZAC]
list = "bgm_doa1_zac, bgm_doa2_zac, bgm_doa3_zac, bgm_doa4_zac"

[TIN]
list = "bgm_doa1_tin_ps, bgm_doa2_tin, bgm_doa3_tin, bgm_doa4_tin"

[JAN]
list = "bgm_doa1_jan, bgm_doa1_jan_ps, bgm_doa2_jan, bgm_doa3_jan, bgm_doa4_jan"

[RYU]
list = "bgm_doa1_ryu, bgm_doa2_ryu, bgm_doa3_ryu, bgm_doa4_ryu"

[KAS]
list = "bgm_doa1_kas, bgm_doa2_kas, bgm_doa3_kas, bgm_doa4_kas"

[HEL]
list = "bgm_doa2_hel, bgm_doa3_hel, bgm_doa4_hel"

[BAS]
list = "bgm_doa2_bas, bgm_doa3_bas, bgm_doa4_bas"

[KOK]
list = "bgm_doa4_hak"

[HYT]
list = "bgm_doa3_hyt, bgm_doa4_hyt"

[LEI]
list = "bgm_doa1_lei, bgm_doa1_lei_ps, bgm_doa2_lei, bgm_doa3_lei, bgm_doa4_lei"

[AYA]
list = "bgm_doa1_aya_ps, bgm_doa2_aya, bgm_doa3_aya, bgm_doa4_aya"

[ELI]
list = "bgm_doa4_boy"
 
[LIS]
list = "bgm_doa4_lis"

[BRA]
list = "bgm_doa3_bra, bgm_doa4_bra"

[CRI]
list = "bgm_doa3_cri, bgm_doa4_cri"

[HTM]
list = "bgm_doa3_kor, bgm_doa4_kor"

[BAY]
list = "bgm_doa1_bay, bgm_doa1_bay_ps, bgm_doa3_bay, bgm_doa4_bay"

[RIG]
list = "bgm_doa5v_rig"

[MIL]
list = "bgm_doa5v_mil"

[MAR]
list = "bgm_doa5a_mar"

[NYO]
list = "bgm_doa5a_nyo"

[HON]
list = "bgm_doa5a_hon"

[RID]
list = "bgm_doa1_rid_ps, bgm_doa1_rid_ps_wo_intro, bgm_doa5a_chb, bgm_doa5a_chb_02"

[DGO]
list = "bgm_doa6_bst01_01"

[NIC]
list = "bgm_doa6_lbn01_01, bgm_doa6_quest"

[PHF]
list = "bgm_doa5_lab03_01_wo_intro"

[MAI]
list = "bgm_doa5lr_female_ninja"

[SNK]
list = "bgm_doa6_female_cyborg"

[MOM]
list = "bgm_doa5u_mom"

[RAC]
list = "bgm_doa5u_rac"

[SKD]
list = "bgm_doa6_skd"

[S0101PIR]
list = "bgm_doa6_pir01_01"

[S0102PIR]
list = "bgm_doa6_pir01_01"

[S0201BST]
list = "bgm_doa6_bst01_01, bgm_doa6_bst01_last"

[S0301CRM]
list = "bgm_doa6_crm01_01"

[S0302CRM]
list = "bgm_doa6_crm01_01"

[S0401CLS]
list = "bgm_doa6_cls01_01, bgm_doa6_cls01_02, bgm_doa6_cls01_03, bgm_doa6_cls_remix"

[S0411CLS]
; Note: the Douglas Memorial stage mod actually gets the list from S0401CLS.
list = "bgm_doa6_cls01_01, bgm_doa6_cls01_02, bgm_doa6_cls01_03, bgm_doa6_cls_remix"

[S0501PAS]
list = "bgm_doa6_pas01_01"

[S0502PAS]
list = "bgm_doa6_pas01_01"

[S0601LBN]
list = "bgm_doa6_lbn01_01"

[S0701MUS]
; Note: bgm_transition_mus is a special music for the game that takes care of changing the music in the different sections of the museum.
list = "bgm_transition_mus"

[S0702MUS]
; Note: bgm_transition_mus is a special music for the game that takes care of changing the music in the different sections of the museum.
list = "bgm_transition_mus"

[S0801LOS]
list = "bgm_doa6_los01_01"

[S0802LOS]
list = "bgm_doa6_los01_01"

[S0901WAY]
list = "bgm_doa6_way01_01"

[S1101BAM]
; Note: bgm_transition_bam is a special music for the game that changes the music between the floors in Miyabi.
list = "bgm_transition_bam"

[S1102BAM]
list = "bgm_doa6_bam02_01, bgm_doa6_bam_remix"

[S1201PRO]
list = "bgm_doa6_pro01_01"

[S1301GYM]
list = "bgm_doa5_gym01_01, bgm_doa6_gym01_01"

[S1501GRD]
list = "bgm_doa6_ttm01_01"

[S1601ISL]
list = "bgm_doa5_isl01_01, bgm_doa5lr_hnb01_01, bgm_doax3_day03_karaoke, bgm_doax3_day06, bgm_doax3_day07, bgm_doax3_night02, bgm_doax3_night03, bgm_doax3_night04, bgm_doax3_night05"


