[Uncensorship]
; HON/MAR/NIC/SNK break blow uncensorship
uncensor_loli_blow = false

[Misc]
; If enabled, info about current slot (and layer 2 mod if any) will be shown in character screen selection.
slot_info_in_css = true
; If enabled, info about current stage slot (and layer2 mod if any) will be shown in stage screen selection
slot_info_in_sss = true

; This allow to set a different stage for survival mode. 
; Default value is default game behavior (colosseum stage)
; The value can be a stage code -> Eg: survival_stage = S1601ISL
; It can also be a mod path -> Eg: survival_stage = "My Stage"
; If your stage is at a subfolder inside Layer2, then that folder name must also be specified -> E.g: survival_stage = "STAGES/My Stage"
; Special stage codes of REDELBE also work. Eg (to load colosseum night): survival_stage = COLNIGHT
survival_stage = S0401CLS

; If true, the splash screen won't be shown.
disable_splash = false

[UI]
; If enabled, the battle HUD can be toggled using F5 key.
enable_hide_battle_hud = true

[Random]
; if enabled, Layer2 costume mods will count towards random selection of costumes (both player and cpu).
enable_random_costume_mods = true
; if enabled, and the costume (either vanilla or mod) has alternative underwears, the underwear will be randomized in random selections (both player and cpu)
enable_random_underwear = false
; If enabled, randomization will be applied to hair styles in random selections (both player and cpu). You can configure further options in [RandomHair]
enable_random_hair = false
; If enable, randmization will be applied to glasses in random selections (both player and cpu). You can configure further options in [RandomGlasses]
enable_random_glasses = false
; If enabled, Layer2 stage mods will count towards random selection of stages (both randomness selected by player or cpu)
enable_random_stage_mods = true
; If enabled, music will be randomized following the rules at [RandomMusic] section
enable_random_music = false

[RandomHair]
;;;;;;;;;
; THIS SECTION IS ONLY MEANINGFUL if enable_random_hair = true in [Random]
; Otherwise, everything in here is ignored.
;;;;;;;;;
;
; This is the percentage that randomization will be applied to hair. 
; If the probability evaluates to true, a random hair, from all available to current costume, will be selected, including the default hair of the current costume.
; If the probability evaluates to false, the default hair for that costume will be selected (default game behavior)
probability = 35
; If true, hair mods will be included in the randomization. If false, they will be excluded.
allow_mods = true

[RandomGlasses]
;;;;;;;;;
; THIS SECTION IS ONLY MEANINGFUL if enable_random_glasses = true in [Random]
; Otherwise, everything in here is ignored.
;;;;;;;;;
;
; This is the percentage that randomization will be applied to glasses.
; For costumes without default glasses, this is the probability that a glasses from the list below will be chosen.
; For costumes with default glasses, this is the probability that a different glasses than default one will be chosen from the list below, and "no glasses" is also added to the random list in this case.
probability = 25
;
; List of glasses for characters. When a random glass is chosen, it will be chosen from the list here.
; You can configure this list to your liking if you want X character to get glasses from other characters.
; Use a "," to separate multiple items
KAS = ITM_GLASSES_KAS_001, ITM_GLASSES_KAS_002, ITM_GLASSES_KAS_003
BAS = ITM_GLASSES_BAS_001, ITM_GLASSES_BAS_002
BAY = ITM_GLASSES_BAY_001, ITM_GLASSES_BAY_002
JAN = ITM_GLASSES_JAN_001, ITM_GLASSES_JAN_002
LEI = ITM_GLASSES_LEI_001
HTM = ITM_GLASSES_HTM_001
RYU = ITM_GLASSES_RYU_001
HYT = ITM_GLASSES_HYT_001
MAR = ITM_GLASSES_MAR_001, ITM_GLASSES_MAR_002, ITM_GLASSES_MAR_003
NIC = ITM_GLASSES_NIC_001, ITM_GLASSES_NIC_002, ITM_GLASSES_NIC_003
KOK = ITM_GLASSES_KOK_001
NYO = ITM_GLASSES_NYO_001, ITM_GLASSES_NYO_002_MASK, ITM_GLASSES_NYO_003_MASK
RID = ITM_GLASSES_RID_001
MIL = ITM_GLASSES_MIL_001, ITM_GLASSES_MIL_002
ZAC = ITM_GLASSES_ZAC_001, ITM_GLASSES_ZAC_002, ITM_GLASSES_ZAC_003, ITM_GLASSES_ZAC_004
TIN = ITM_GLASSES_TIN_001, ITM_GLASSES_TIN_002, ITM_GLASSES_TIN_003, ITM_GLASSES_TIN_004
HEL = ITM_GLASSES_HEL_001, ITM_GLASSES_HEL_002, ITM_GLASSES_HEL_003
AYA = ITM_GLASSES_AYA_001
ELI = ITM_GLASSES_ELI_001
LIS = ITM_GLASSES_LIS_001, ITM_GLASSES_LIS_002, ITM_GLASSES_LIS_003, ITM_GLASSES_LIS_004, ITM_GLASSES_LIS_005, ITM_GLASSES_LIS_006
BRA = ITM_GLASSES_BRA_001
CRI = ITM_GLASSES_CRI_001, ITM_GLASSES_CRI_002
RIG = ITM_GLASSES_RIG_001
HON = ITM_GLASSES_HON_001, ITM_GLASSES_HON_002
DGO = ITM_GLASSES_DGO_001, ITM_GLASSES_DGO_002
PHF = ITM_GLASSES_PHF_001
MOM = ITM_GLASSES_MOM_001
RAC = ITM_GLASSES_RAC_001, ITM_GLASSES_RAC_002
SKD = ITM_GLASSES_SKD_001

[RandomMusic]
;;;;;;;;;
; THIS SECTION IS ONLY MEANINGFUL if enable_random_music = true in [Random]
; Otherwise, everything in here is ignored.
;;;;;;;;;
;
; The mode. Currently, this can be one of these two values: mix and full
; mix -> the music will be randomized between the stage or character bgm, where the probability for the stage is given by "mix_stage_probability", and the
; probability for character music is 100 - mix_stage_probability 
; full -> the music will be chosen randomly from the list in the file REDELBE/random_tracks.txt
; fullmix -> the music will be randomized based by character/stage from the list in the file REDELBE /fullmix.ini.
mode = fullmix
; If mode is mix or fullmix, this is the probability that the stage theme will be chosen over the character theme.
; Please note that if the characters don't have a theme, this effectively becomes 100.
stage_probability = 50

[Debug]
; Logs access to virtualized files (the files in REDELBE dir). This includes both replacer mods, and Layer2 mods.
; For Layer2 mods, the log_virtual will also print the mod name which contains the file.
; Cost: minimal
log_virtual = false
; Logs access to .rdb external files (the .rdb files that are stored in game data/ folder).
; These are usually audio/video files.
; Cost: minimal
log_external = false
; Logs access to .rdb internal files (files in the .rdb.bin* files)
; Cost: average. 
log_internal = false
; Logs access to the (mostly encrypted) .bin files in numeric folders (these are outside rdb filesystem)
; Unlike other log options, this one will be logged in every read attempt along with file position and number of bytes requested.
; Cost: irrelevant except when playing videos of story mode, where it would become low/average.
log_numeric = false


;;;;;;;;;;; FROM HERE IT IS ADVANCED STUFF. DO NOT TOUCH IF YOU DON'T KNOW WHAT THESE SETTINGS MEAN ;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Enables exception handler (will log a crash to the log file).
enable_exception_handler = false

; If enabled, REDELBE will be able to print a C++ exception message to the log file, before the game does a "high level crash".
enable_cpp_exception_hook = false
; If enable_cpp_exception_hook=true, REDELBE will (try to) trace back this many calls when the exception happens.
cpp_exception_stack_trace_level = 3

; Encryption
; Dumps all AES256-CBC keys/IV to the log file.
dump_keys = false

; Dumps all encrypted content after it has been decrypted.
; Data is stored in REDELBE/DECRYPTED.
dump_all_decrypted = false
; If true, and zlib data is detected after decryption, it will be automatically uncompressed before being dumped (this setting won't do anything unless dump_all_decrypted = true)
auto_uncompress_decrypted = true

; Prints to the log the script calls to native functions (and only native), for debugging purposes.
; WARNING: this will cause a LOT of writes to the log file. It may slow down the game, specially on low spec systems. 
; Also, the log file size will increase a lot, only enable this for short game sessiones (< 5 minutes).
debug_script = false

; It will print to the log the call to the string hash functions.
hunt_hashes = false

; DO -->NOT<-- ENABLE this, unless you hit your head hard or you want the log file reach the stratosphere.
;debug_threading = false

